apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-keyvault
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: keyvault
    spec:
      containers:
      - image: alpine:latest
        name: test-app
        command: ["/bin/sh", "-c", "--"]
        args: ["while true; do sleep 5; done;"]
        volumeMounts:
        - name: secrets
          mountPath: /secrets
          readOnly: true

      initContainers:
      - name: keyvault-agent
        image: <IMAGE_PATH>
        env:
        - name: VAULT_BASE_URL
          value: <VAULT_URL>
        - name: SERVICE_PRINCIPLE_FILE_PATH
          value: /host/azure.json
        - name: SECRETS_FOLDER
          value: /secrets
        - name: SECRETS_KEYS
          value: <SECRET_KEYS>

        volumeMounts:
        - name: secrets
          mountPath: /secrets

        - name: host-sp
          mountPath: /host/azure.json
          readOnly: true
      volumes:
      - name: secrets
        emptyDir:
          # we want the secrets to reside only in-memory
          medium: Memory

      - name: host-sp
        hostPath:
          # this file contains the cluster service-principal, it exists on every node by default
          path: /etc/kubernetes/azure.json
          type: File